### ISSUE TITLE
Needs a hint to actually use the '.select' method

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/phase-3-anagram-detector#3]
### Canvas Link

https://learning.flatironschool.com/courses/5286/assignments/172592?module_item_id=376658

### Concern

This lab's hints aren't that great.

This needs a more obvious hint to use the '.select' method as well as the idea of chaining methods together.

### Suggested Changes

Hint:
- Use a method like '.select' that allows you to iterate through the words of the array

Hint: 
- Use the idea of chaining to chain several methods together

**Comment by lizbur10** [comment]
Hi there,

Thank you for your feedback! The Phase 3 content is currently in the process of being updated, so we will take this information into consideration as we proceed.

As always, thanks for contributing! 💙
